MINOR FOUNDATIONS:   Require Issue Or Task

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,6 +28,7 @@ env:
     }}
 jobs:
   label:
+    name: Label
     runs-on: ubuntu-latest
     steps:
     - name: Apply Label
@@ -101,6 +102,54 @@ jobs:
     permissions:
       contents: read
       pull-requests: write
+  requireIssueOrTask:
+    name: Require Issue Or Task Association
+    runs-on: ubuntu-latest
+    steps:
+    - name: Check out
+      uses: actions/checkout@v3
+    - name: Get PR Information
+      id: get_pr_info
+      uses: actions/github-script@v6
+      with:
+        script: >2-
+              const pr = await github.rest.pulls.get({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                pull_number: context.payload.pull_request.number
+              });
+
+              const prOwner = pr.data.user.login || "";
+              const prBody = pr.data.body || "";
+              core.setOutput("prOwner", prOwner);
+              core.setOutput("description", prBody);
+              console.log(`PR Owner: ${prOwner}`);
+              console.log(`PR Body: ${prBody}`);
+    - name: Check For Associated Issues Or Tasks
+      id: check_for_issues_or_tasks
+      if: ${{ steps.get-pr.outputs.prOwner != 'dependabot[bot]' }}
+      run: >2-
+            PR_BODY="${{ steps.get-pr.outputs.description }}"
+            echo "::notice::Raw PR Body: $PR_BODY"
+
+            if [[ -z "$PR_BODY" ]]; then
+              echo "Error: PR description does not contain any links to issue(s)/task(s) (e.g., 'closes #123' / 'closes AB#123' / 'fixes #123' / 'fixes AB#123')."
+              exit 1
+            fi
+
+            PR_BODY=$(echo "$PR_BODY" | tr -s '\r\n' ' ' | tr '\n' ' ' | xargs)
+            echo "::notice::Normalized PR Body: $PR_BODY"
+
+            if echo "$PR_BODY" | grep -Piq "((close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)\s*(\[#\d+\]|\#\d+)|(?:close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)\s*(\[AB#\d+\]|AB#\d+))"; then
+              echo "Valid PR description."
+            else
+              echo "Error: PR description does not contain any links to issue(s)/task(s) (e.g., 'closes #123' / 'closes AB#123' / 'fixes #123' / 'fixes AB#123')."
+              exit 1
+            fi
+      shell: bash
+    permissions:
+      contents: read
+      pull-requests: read
   build:
     runs-on: ubuntu-latest
     steps:
@@ -109,7 +158,7 @@ jobs:
     - name: Setup .Net
       uses: actions/setup-dotnet@v3
       with:
-        dotnet-version: 7.0.201
+        dotnet-version: 9.0.100
     - name: Restore
       run: dotnet restore
     - name: Build
